# Generated by Django 4.2.5 on 2023-09-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
                ('object_translation', models.CharField(max_length=200)),
            ],
        ),
    ]
